language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ravishk17/partypros -f ./partypros/Dockerfile.dev ./partypros

script:
    - docker run -e CI=true ravishk17/partypros npm run test

after_success:
    - docker build -t ravishk17/multi-partypros ./partypros
    - docker build -t ravishk17/multi-nginx ./nginx
    - docker build -t ravishk17/multi-backend ./backend

    #Log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push ravishk17/multi-partypros
    - docker push ravishk17/multi-nginx
    - docker push ravishk17/multi-backend



#RDS
# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "partypros"
#     env: "Partypros-env"
#     bucket_name: "elasticbeanstalk-us-east-2-119094900355"
#     bucket_path: "partypros"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY